services:
  backend:
    image: ${DOCKERHUB_USERNAME}/k8app-backend:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      APP_URL: ${APP_URL}
      PORT: "8080"

  nginx:
    image: ${DOCKERHUB_USERNAME}/k8app-nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

# No mount volume or Db service image required as i use supabase for db and storage.