name: Ritvik's CI Workflow

on:
    push:
jobs:
    build:
        #job name
        runs-on: ubuntu-latest
        steps:
            #Step 1
            -name: Checksout Code
            -uses: actions/checkout@v4
            #Step 2
            -name: Setup Docker
            -uses: docker/setup-buildx-action@v3
          
